### PR TITLE
[Hotfix] Default URL Headers (#36), Docker Image to 1.29, Missing config in Configmap added, OIDC Plugin Name added, Fix Pre Built Deployment File Mounting (#37), GHCR Image Push (#39)

### LINKED ISSUE #36: Authority and Path headers not present

### LINKED ISSUE #37: Pre Built Deployment: Mounting `envoy.yaml` to `/etc/envoy/` overwrites plugin directory.

### LINKED ISSUE #38: Refresh Token is optional

### LINKED ISSUE #39: GHCR Image
Also push image to Github Container Registry

### PR DESCRIPTION
**Pull request by antonengelhardt**
- Closes #36: Sometimes envoy does not send `:authority`: https://github.com/kubernetes/ingress-nginx/issues/3706
- Closes #37: Do not overwrite `/etc/envoy` when mounting `envoy.yaml` (applies for pre built deployment template): https://stackoverflow.com/a/63418581
- Closes #38: Optional Refresh token
- Closes #39: Also push image to GHCR
- Bump Docker Base Image to 1.29
- Plugin Config was missing in Configmap
- Plugin Name changed

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -269,6 +270,23 @@ impl ConfiguredOidc {
         return None;
     }
 
+    /// Get the host of the HTTP request
+    /// The host is searched in the request headers. If the host is found, the value is returned.
+    fn get_host(&self) -> Option<String> {
+
+        let host = if self.get_http_request_header(":authority").is_some() {
```
Comment (miwig) [inline src/lib.rs:277]: You could do this with a chain of [`or_else`](https://doc.rust-lang.org/std/option/enum.Option.html#method.or_else) calls. 
```rust
let host = self.get_http_request_header(":authority")
    .or_else(|| self.get_http_request_header("X-Forwarded-Host"))
    .or_else(|| self.get_http_request_header("host"));
```
